services:
  redis-primary:
    image: docker.io/bitnami/redis:7.2
    container_name: redis-primary
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=mypass
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - banknet

  redis-secondary:
    image: docker.io/bitnami/redis:7.2
    container_name: redis-secondary 
    ports:
      - '6379'
    depends_on:
      - redis-primary
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=mypass
      - REDIS_PASSWORD=mypass
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - banknet      
  
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight 
    ports:
      - '8001:8001'
    networks:
      - banknet

volumes:
  redis_data:
    driver: local
    
networks:
  banknet:
    driver: bridge
    ipam:
      driver: default
