services:
  redis-primary:
    image: registry.gitlab.com/armdev/dockers/redis:7.2
    container_name: redis-primary
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=PkAX16o639vwj5u
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'

  redis-secondary:
    image: registry.gitlab.com/armdev/dockers/redis:7.2
    container_name: redis-secondary
    ports:
      - '6379'
    depends_on:
      - redis-primary
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=PkAX16o639vwj5u
      - REDIS_PASSWORD=PkAX16o639vwj5u
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL      
 
 
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest   
    restart: always
    environment:
      - REDIS_HOSTS=redis-primary:6379
    ports:
      - "8082:8081"
#      
#  redisinsight:
#    image: redislabs/redisinsight
#    container_name: redisinsight
#    links:
#      - redis-primary
#      - redis-secondary
#    ports:
#      - '9081:8001'

volumes:
  redis_data:
    driver: local
